Updated yaml syntax.

diff --git a/.github/workflows/aws-account-info.yml b/.github/workflows/aws-account-info.yml
--- a/.github/workflows/aws-account-info.yml
+++ b/.github/workflows/aws-account-info.yml
@@ -24,35 +24,35 @@ jobs:
           role-to-assume: arn:aws:iam::098789448788:role/rgonzo-aws-accounts-github-Role-RkgjO4uXfipb
           aws-region: us-east-1  # Adjust region as needed
 
-    - name: Retrieve AWS Account List
-      id: aws_accounts
-      run: |
-        # Retrieve and encode the accounts list as a single line
-        accounts=$(aws organizations list-accounts --query "Accounts[*].{ID:Id,Name:Name}" --output json | base64)
-        echo "Retrieved accounts: $accounts"
-        
-        # Check if the accounts variable is empty
-        if [[ -z "$accounts" || "$accounts" == "[]" ]]; then
-          echo "No accounts found or command failed."
-          exit 1
-        fi
+      - name: Retrieve AWS Account List
+        id: aws_accounts
+        run: |
+          # Retrieve and encode the accounts list as a single line
+          accounts=$(aws organizations list-accounts --query "Accounts[*].{ID:Id,Name:Name}" --output json | base64)
+          echo "Retrieved accounts: $accounts"
+          
+          # Check if the accounts variable is empty
+          if [[ -z "$accounts" || "$accounts" == "[]" ]]; then
+            echo "No accounts found or command failed."
+            exit 1
+          fi
+  
+          # Write the Base64 encoded accounts list to the environment file
+          echo "accounts=$accounts" >> $GITHUB_ENV
 
-        # Write the Base64 encoded accounts list to the environment file
-        echo "accounts=$accounts" >> $GITHUB_ENV
-
-    - name: Update Markdown Document
-      run: |
-        markdown_file="accounts.md"
-        
-        # Decode the accounts JSON from Base64
-        accounts=$(echo "${{ env.accounts }}" | base64 --decode)
-        
-        echo "# AWS Accounts" > $markdown_file
-        echo "Here is the list of AWS accounts in the organization:" >> $markdown_file
-        echo "" >> $markdown_file
-        
-        # Append each account to the markdown file
-        echo "$accounts" | jq -r '.[] | "* \(.Name) (\(.ID))"' >> $markdown_file
+      - name: Update Markdown Document
+        run: |
+          markdown_file="accounts.md"
+          
+          # Decode the accounts JSON from Base64
+          accounts=$(echo "${{ env.accounts }}" | base64 --decode)
+          
+          echo "# AWS Accounts" > $markdown_file
+          echo "Here is the list of AWS accounts in the organization:" >> $markdown_file
+          echo "" >> $markdown_file
+          
+          # Append each account to the markdown file
+          echo "$accounts" | jq -r '.[] | "* \(.Name) (\(.ID))"' >> $markdown_file
           
       - name: Debug - List Files After Generation
         run: |
